#!/usr/bin/env bash
# This script is displaying loops from 1 to 10 times
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

i=0

while [ $i -le 12 ]
do
	echo "Hour: $i"
	j=1
	while [ $j -le 59 ]
	do
		echo "$j"
		j=$(( j + 1))
	done
	i=$(( i + 1 ))
done
